################################################################################
#
################################################################################
service: dpnt-sourcecode

provider:
    name: aws
    runtime: java8
    stage: ${opt:stage, 'local'}
    region: eu-west-2

    memorySize: 1536 # in MB
    timeout: 120 # in seconds
    versionFunctions: false
    environment: ${file(config/env.${self:provider.stage}.yml)}

package:
    artifact: build/libs/dpnt-sourcecode-all.jar

functions:
    srcs-github-export:
        handler: tdl.datapoint.sourcecode.SourceCodeUploadHandler
        onError: arn:aws:sns:eu-west-2:577770582757:MyselfEU2
        events:
          - existingS3:
              bucket: BUCKET_NAME
              events:
                - s3:ObjectCreated:*
              rules:
                - prefix: images/
                - suffix: .jpg