service: srcs-github-export

provider:
    name: aws
    runtime: java8

package:
    artifact: build/distributions/tdl-srcs-github-export.zip

functions:
    srcs-github-export:
        #TODO:
        # - Rename handler when new function added
        # - Add external S3 event attaching plugin
        # - Configure memory and timeout
        handler: tdl.datapoint.sourcecode.Handler