################################################################################
#
################################################################################
service: dpnt-sourcecode

config:
  s3BucketARN: ${file(config/env.${self:provider.stage}.yml):S3_BUCKET_ARN}
  sqsQueueARN: ${file(config/env.${self:provider.stage}.yml):SQS_QUEUE_ARN}

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, 'local'}
  region: eu-west-2

  memorySize: 1536 # in MB
  timeout: 120 # in seconds
  versionFunctions: false
  environment: ${file(config/env.${self:provider.stage}.yml)}

  iamRoleStatements:

    # List SRCS bucket
    - Effect: "Allow"
      Action:
       - "s3:ListBucket"
       - "s3:ListBucketMultipartUploads"
      Resource:
       - ${self:config.s3BucketARN}

    # Read SRCS bucket
    - Effect: "Allow"
      Action:
       - "s3:GetObject",
      Resource:
        Fn::Join:
          - ""
          - - ${self:config.s3BucketARN}
            - "/*"

    # Publish events
    - Effect: "Allow"
      Action:
       - "sqs:GetQueueAttributes"
       - "sqs:SendMessageBatch"
       - "sqs:SendMessage"
      Resource:
       - ${self:config.sqsQueueARN}

package:
  artifact: build/libs/dpnt-sourcecode-all.jar

functions:
  srcs-github-export:
    handler: tdl.datapoint.sourcecode.SourceCodeUploadHandler
    onError: arn:aws:sns:eu-west-2:577770582757:MyselfEU2