S3_ENDPOINT:
S3_REGION:
S3_ACCESS_KEY:
S3_SECRET_KEY:

SQS_ENDPOINT:
SQS_REGION:
SQS_ACCESS_KEY:
SQS_SECRET_KEY:
SQS_QUEUE_URL:

GITHUB_HOST:
GITHUB_PORT:
GITHUB_PROTOCOL:
GITHUB_AUTH_TOKEN:
GITHUB_REPO_OWNER: